services:
  # Il Backend + Frontend (Node.js)
  - type: web
    name: domy-app
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.0
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false # Ti chiederà di inserirlo manualmente (URL di Neon)
      - key: DIRECT_URL
        sync: false # Ti chiederà di inserirlo manualmente (URL di Neon)

version: "1"
